version: '3.8'

services:
  database:
    image: postgres
    container_name: restaurant-db-container
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'restaurant-db'
